# Generated by Django 3.1.6 on 2021-02-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service',
            old_name='file',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='user_service',
            name='file2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_service',
            name='file3',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
