# Generated by Django 3.1.6 on 2021-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_service_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='title',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
