# Generated by Django 3.1.6 on 2021-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210224_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='country',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='email',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='in_progress',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='services',
            field=models.CharField(blank=True, choices=[('Home Work', 'Home Work'), ('Project', 'Project'), ('Course', 'Course')], max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='solving',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='subject',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
