# Generated by Django 3.1.6 on 2021-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210224_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='country',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='email',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file3',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='whatsapp_number',
            field=models.IntegerField(),
        ),
    ]
