# Generated by Django 3.1.6 on 2021-02-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_auto_20210224_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='country',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='delivery_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='file3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='in_progress',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='services',
            field=models.CharField(blank=True, choices=[('Home Work', 'Home Work'), ('Project', 'Project'), ('Course', 'Course')], max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='solving',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='subject',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='whatsapp_number',
            field=models.IntegerField(blank=True),
        ),
    ]
