# Generated by Django 3.1.6 on 2021-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210224_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
