# Generated by Django 3.1.6 on 2021-02-24 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0016_auto_20210224_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_service',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='user_service',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='user_service',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='user_service',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='user_service',
            name='solving',
        ),
        migrations.AlterField(
            model_name='user_service',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='country',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='email',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='services',
            field=models.CharField(blank=True, choices=[('Home Work', 'Home Work'), ('Project', 'Project'), ('Course', 'Course')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
