# Generated by Django 3.1.6 on 2021-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210224_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='solving',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75, null=True),
        ),
    ]
