# Generated by Django 3.1.6 on 2021-02-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210225_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='solving',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
    ]
