# Generated by Django 3.1.6 on 2021-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20210225_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='accepted',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='finished',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='in_progress',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='rejected',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
    ]
