# Generated by Django 3.1.6 on 2021-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210225_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
