# Generated by Django 3.1.6 on 2021-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20210225_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='Price',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=75),
        ),
    ]
