# Generated by Django 3.1.6 on 2021-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_user_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='Price',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
