# Generated by Django 3.1.6 on 2021-02-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20210227_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='solution_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
