# Generated by Django 3.1.6 on 2021-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20210228_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='solution_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
