# Generated by Django 3.1.6 on 2021-02-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20210228_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service',
            old_name='solution_file',
            new_name='solution_file_1',
        ),
        migrations.AddField(
            model_name='user_service',
            name='solution_file_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_service',
            name='solution_file_3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='services',
            field=models.CharField(choices=[('Home Work', 'Home Work'), ('Project', 'Project'), ('Course', 'Course'), ('Assignment', 'Assignment'), ('Lab', 'Lab')], max_length=75, null=True),
        ),
    ]
