# Generated by Django 3.1.6 on 2021-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20210301_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='payment_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
