# Generated by Django 3.1.6 on 2021-03-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_user_service_payment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='payment_link',
            field=models.TextField(null=True),
        ),
    ]
