# Generated by Django 3.1.6 on 2021-03-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20210304_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service',
            old_name='payment_link',
            new_name='payment_link_Knet',
        ),
    ]
