# Generated by Django 3.1.6 on 2021-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20210304_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='payment_link_visa',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
