# Generated by Django 3.1.6 on 2021-03-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_user_service_payment_link_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='delivery_date',
            field=models.TextField(null=True),
        ),
    ]
