# Generated by Django 3.1.6 on 2021-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20210304_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='payment_link_Knet',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_service',
            name='payment_link_visa',
            field=models.CharField(max_length=300),
        ),
    ]
