# Generated by Django 3.1.6 on 2021-03-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20210304_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service',
            name='payment_link_Knet',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user_service',
            name='payment_link_visa',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
